name: daniellesdoggrooming
description: Dog Grooming Management App.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  fab_circular_menu: ^1.0.1
  sqflite: ^1.3.2+1
  font_awesome_flutter: ^8.11.0
  image_picker: ^0.6.7+17
  image: ^2.1.19
  path_provider: ^1.6.24
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  uuid: ^2.2.2
  intl: ^0.16.1
  flutter_picker: ^1.1.5
  downloads_path_provider: ^0.1.0
  path: ^1.7.0
  flutter_swiper: ^1.1.6
  video_player: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
