name: daniellesdoggrooming
description: Dog Grooming Management App.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  fab_circular_menu: ^1.0.1
  sqflite: ^1.3.2+1
  font_awesome_flutter: ^8.11.0
  image_picker: ^0.6.7+17
  image: ^2.1.19
  path_provider: ^1.6.24
  http: ^0.12.2
  shared_preferences:
  uuid: ^2.2.2
  flutter_picker: ^1.1.5
  path: ^1.7.0
  video_player: ^1.0.1
  meta: '>=1.1.0 <2.0.0'
  redux: ^4.0.0
  flutter_local_notifications: ^1.4.1
  flutter_redux: ^0.6.0
  key_value_store_flutter:
  rxdart: ^0.23.1
  redux_persist: ^0.8.3
  intl: ^0.16.1
  sqfentity: ^1.4.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
